name: node1
data_dir: "./data/"

logger:
  stdout: true
  level: "debug"
  max_age: 30
  max_size: 100
  rotation: false


metrics:
  reporting_freq_sec: 60
  namespace: "nakama"
  prometheus_port: 0

database:
  address:
    - "root:sparkinfi123!@192.168.102.223:5432/nakama-plus"
  conn_max_lifetime_ms: 0
  max_open_conns: 0
  max_idle_conns: 100

runtime:
  path: "./data/modules"
  http_key: "http_key"
  #js_entrypoint: "anys.js"

socket:
  server_key: "sparkgame"
  port: 7350
  max_message_size_bytes: 4096 # bytes
  read_timeout_ms: 30000
  write_timeout_ms: 30000
  idle_timeout_ms: 60000
  write_wait_ms: 5000
  pong_wait_ms: 25000
  ping_period_ms: 15000 # Must be less than pong_wait_ms
  outgoing_queue_size: 16

session:
  encryption_key: "encryption_key"
  token_expiry_sec: 7200
  refresh_encryption_key: "refresh_encryption_key"
  refresh_token_expiry_sec: 2592000
  single_socket: true

social:
  steam:
  publisher_key: ""
  app_id: 0

console:
  port: 7351
  signing_key: "signing_key"

matchmaker:
  max_tickets: 2
  interval_sec: 15
  max_intervals: 3

iap:
  apple:
    shared_password: "a512ae481d344c5db921c8e049aef419"
    server_api_key_id: "2DB4KVP297"
    server_api_issuer_id: "31e310f9-da91-4a17-8709-e19e7da0dffa"
    server_api_bundle_id: "com.zeusai.starhold"
    server_api_private_key: |
      -----BEGIN PRIVATE KEY-----
      MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgr09jpJ8+IsuYxnZS
      AzF6q0XzltlbauCn2DUDttSrEUOgCgYIKoZIzj0DAQehRANCAASIFcQ19NguHay9
      Y6ePjRo/rwHoHhS5kS1OuHic4c6s3BrjLOf5UdXJUJp1pAMqQJuXdRAPlPo8R0Vx
      2hnUp9hg
      -----END PRIVATE KEY-----
  google:
    client_email: "email@google.com"
    private_key: "pk"
  huawei:
    public_key: "pk"
    client_id: "id"
    client_secret: "secret"

#cluster:
#  gossip_bindaddr: "0.0.0.0"
#  gossip_bindport: 7335
#  gossip_advertise_addr: "192.168.102.8" # 跨主机部署时必填：对端可访问的本机 IP
#  etcd:
#    endpoints:
#      - "0.0.0.0:2379"


  grpc:
    access_token: "test"
    heartbeat_timeout: 15
    ca_cert: "./data/cert/CA.pem"
    server_name_override: "example.com"

  cache:
    prefix: "nakama"

ledger:
  wallet_ledger_max_items: 3
  wallet_ledger_max_age_days: 1
  inventory_ledger_max_items: 3
  inventory_ledger_max_age_days: 1
